### ISSUE TITLE
Won't draw strider answer

### ISSUE THREAD

**Issue by cbizon** [ranking-agent/gamma-viewer#1]
On this query: 
```
query_graph = {
    "nodes": [
        {
            "id": "a",
            "type": "disease",
            "curie": "MONDO:0005015"
        },
        {
            "id": "b",
            "type": "gene"
        },
        {
            "id": "c",
            "type": "chemical_substance"
        }
    ],
    "edges": [
        {
            "id": "ab",
            "source_id": "a",
            "target_id": "b",
            "type": "gene_associated_with_condition",
        },
        {
            "id": "bc",
            "source_id": "c",
            "target_id": "b",
            "type": "decreases_activity_of"
        }
    ]
    }
```

sent to strider, and waiting for the first few results, and then sending that message to GammaViewer gives a "BadMessage" Error.

The problem seems to be that strider is adding curie:None to nodes b & c in the question graph. If those are deleted, then gamma viewer can draw it.

**Comment by maximusunc** [comment]
The JSON validation is based off of Translator Reasoners API version 0.9.2. More informative validation error messaging has also been added. Closing for now, but feel free to reopen if you think we need to support more types of messages.
