### ISSUE TITLE
crashes on multi-type node

### ISSUE THREAD

**Issue by cbizon** [ranking-agent/gamma-viewer#11]
after going to answercoalescence, we can have nodes in the query_graph that look like:

```
{'id': 'extra_qn_0', 'type': ['named_thing', 'biological_entity', 'disease', 'disease_or_phenotypic_feature']}
```

But the viewer doesn't like that array of types, and won't work unless I replace it with a single type.

**Comment by maximusunc** [comment]
This should be fixed in version 0.2.0, which is TRAPI 1.0 compliant and can handle lists of categories.
