### ISSUE TITLE
crashing the viewer

### ISSUE THREAD

**Issue by cbizon** [ranking-agent/gamma-viewer#8]
The output from answer coalescence is causing the viewer to crash. This might be (is probably?) a problem with the json I'm generating, but I'm not sure where.  This is the json I am sending to the viewer:

(outdated json removed)

The viewer shows the question fine, but when I click on the other tabs, everything vanishes.

You can see the whole thing in https://github.com/ranking-agent/AnswerCoalesce/blob/master/documentation/experiments/Famotidine.ipynb. 
(You have to be on the renci vpn to reach robokop messenger though.)

**Comment by cbizon** [comment]
Here's an updated json after fixing some bugs in Answer Coalescer (still crashes gamma viewer though)

[ontology_output.json.txt](https://github.com/ranking-agent/gamma-viewer/files/5001514/ontology_output.json.txt)

**Comment by maximusunc** [comment]
This might have been due to the answers having sets. But update it to TRAPI 1.0 and try it with v0.2.0 and see if it works. If it doesn't, please post the updated json here and I will take a look at it.
